### ISSUE TITLE
Обновите плз документацию по установке плагина

### ISSUE THREAD

**Issue by UstyuzhaninAV** [ItgLvb/teamcity-telegram-plugin#2]
Обновите плз документацию по установке плагина

**Comment by ItgLvb** [comment]
Здравствуйте. Обновлю, как только будет выпущен свежий релиз. Все последние правки собирались и тестировались локально. А текущие релизы принадлежат первоначальному автору проекта. Так что ссылки действительные.

**Comment by UstyuzhaninAV** [comment]
подскажете может в чем проблема? При проведении теста подключения, получаю ошибку

```
Can't send test message to Telegram:
\n not found: limit=0 content=…
```

**Comment by ItgLvb** [comment]
Обновил скриншот админки, и ссылку на релизы.
По ошибке - для анализа необходима хотя бы информация о том, какие поля в настройках плагина заполнены. Лучше создать ещё один issue, с более детальной информацией.
