### ISSUE TITLE
Emoji

### ISSUE THREAD

**Issue by SineFine** [ItgLvb/teamcity-telegram-plugin#4]
How to add emoji?

**Comment by ItgLvb** [comment]
Hi. 
https://www.jetbrains.com/help/teamcity/2020.1/customizing-notifications.html#Notification+Templates+Location
I think you need to customize your templates.
In telegram-plugin-server/src/test/java/com/notononoto/teamcity/telegram/web/TelegramSendMessageTest.java, the author of the commit used Unicode characters.
